PM_USER: ENC[AES256_GCM,data:Xe9W2O7zhFT6C64ImWwTGC65,iv:rGKH4+f7QgXMLd1pe5mbpgt7SLaf51C+kkQG7M+lwWw=,tag:vMpQ0OmclLO5/4ob6p4BGA==,type:str]
PM_PASS: ENC[AES256_GCM,data:r41P2dY0EwM=,iv:VcHI7XUAluUAc7ctGF4h+/wbV3/GVY0FLYu83I19GIk=,tag:NpWBRcnAkUy1k5ZLCiEdyw==,type:str]
MINIO_USERNAME: ENC[AES256_GCM,data:LBInQveXxH94LQ==,iv:kB24aMW6/640pm0wzcTKGLnYGWKspVBMqT1qd+CB9aA=,tag:a2UKx9KBzHoTwTsjHLaxtg==,type:str]
MINIO_PASSWORD: ENC[AES256_GCM,data:BD8wB1soUYUEpKBQtg==,iv:9YVIs/vUgJ9yHznW+gaqLeIMfYt0xE4kunOojYhpbJE=,tag:cWyjDxQwAlUeK3qOPqLXBQ==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3uiQdA==,iv:VCyGX77X0b78qnd8Q3T3s2W8U0Tt2v3EOJVpnnMUEts=,tag:GqCgdKlKklL1orHmXr4jFA==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tGxYgwP2SEIrmZqXjP9Qpr+X1Ene6ZhE,iv:dpkc29XJZePrHQYvm0qijgyBHz0IZ78mCeYMaCmP8BM=,tag:rocWMuNE2iZNKdpBpxXmBA==,type:str]
PROXMOX_API_TOKEN: ENC[AES256_GCM,data:yU2VuGNfp+iFDuNlJ7tmWy61sQuRAXcmoJ+Sw2ip5aobZsveFJJHvGfWoOSn5QKGkhc=,iv:RoOfvyVkJUFG5LcH1VeJSl8c4CFP56jT6yRNpNdEwYA=,tag:pdf68mpJeZAtrH9KsOxYRg==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGs3dnNRRGoxZ3NCZWxj
            cDIyV3BNZnRCSVBYQVZyKytmRTY0aXRXNFNFCkpVVWtjTXF1YW51Y2U2L0NIcnNw
            NldyWFBadFBhR2JZY2hJa3UxQlY3ZEUKLS0tIEZTa3REMEE1NFFQNHE2RXZRRmpU
            Q1FIempZanpZNlRkRHJaL2h3bXp2T0UKlkxqr7LfA0+aaqyx1RABVdQq4E+Jc/df
            uG1tJOs5A8VPTO+4/fy0U0U7worgZaCEIliBld0ecO2MYnfK78/NnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T13:44:51Z"
    mac: ENC[AES256_GCM,data:VGsTkjB/tglB9YK1wvUc3hcb4/DfV3/df5DGG4kv8E79iIo1rfy73ICf7Ldt70s9nuxOYF1sLXHVkQ15KW+zp6DcFR8JCVN1865WNgRqBgCW3D8eEx5+7Cf8i2SmXquGiFA0Mozo/0NWGRTyPySY4mKI9/Dtdflz760uPUOFlM8=,iv:ef/E6W9t13R5sXeOGC5lBPIZDM8T/8d+bDPxbH3hUrk=,tag:efgXO4uGgePNU6oYFaVbrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
