PM_USER: ENC[AES256_GCM,data:Xe9W2O7zhFT6C64ImWwTGC65,iv:rGKH4+f7QgXMLd1pe5mbpgt7SLaf51C+kkQG7M+lwWw=,tag:vMpQ0OmclLO5/4ob6p4BGA==,type:str]
PM_PASS: ENC[AES256_GCM,data:r41P2dY0EwM=,iv:VcHI7XUAluUAc7ctGF4h+/wbV3/GVY0FLYu83I19GIk=,tag:NpWBRcnAkUy1k5ZLCiEdyw==,type:str]
MINIO_USERNAME: ENC[AES256_GCM,data:LBInQveXxH94LQ==,iv:kB24aMW6/640pm0wzcTKGLnYGWKspVBMqT1qd+CB9aA=,tag:a2UKx9KBzHoTwTsjHLaxtg==,type:str]
MINIO_PASSWORD: ENC[AES256_GCM,data:BD8wB1soUYUEpKBQtg==,iv:9YVIs/vUgJ9yHznW+gaqLeIMfYt0xE4kunOojYhpbJE=,tag:cWyjDxQwAlUeK3qOPqLXBQ==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3uiQdA==,iv:VCyGX77X0b78qnd8Q3T3s2W8U0Tt2v3EOJVpnnMUEts=,tag:GqCgdKlKklL1orHmXr4jFA==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tGxYgwP2SEIrmZqXjP9Qpr+X1Ene6ZhE,iv:dpkc29XJZePrHQYvm0qijgyBHz0IZ78mCeYMaCmP8BM=,tag:rocWMuNE2iZNKdpBpxXmBA==,type:str]
PROXMOX_VE_API_TOKEN: ENC[AES256_GCM,data:KofwtBix/1EmTEkA0RA4z5M0jm09t0mfV56HUlK+dwgdAmQkdIy3iodxiN36Y2HQlhg=,iv:F9TbBAzx2FdeXdO6h1w7+VpjB6ok7UWzWZmyTrYrBcc=,tag:IndXdMaxIwifD97AWe4NPA==,type:str]
PROXMOX_VE_ENDPOINT: ENC[AES256_GCM,data:51yKx1eWBVeIg6bnNdM22VwtJ9973rUfGVOknqpIMxO4VA==,iv:Uzl7ma6DApAfwCpmOaralWUWtJEIBKs3g13cTZW8zJ8=,tag:QIrIWgderi+8iiXbnMfi6w==,type:str]
PROXMOX_VE_INSECURE: ENC[AES256_GCM,data:qACRkA==,iv:1C8rwB4gsFpOLYW53uUrKrzt81lDHBMScddnSvc79vo=,tag:sMB7a7GOU53Sf6f/mmqGGw==,type:bool]
TF_VAR_dns_key_secret: ENC[AES256_GCM,data:MLm0Uomepeyykx1uKtxeLo7ufH+bm4TJc9ERtdJa2E/0Eqox8iEZCeLz3qBMztQiAM3phqwlyjnnsKVEXov6Qlqiq8Qw6psC6O50QzRQDbazpaaMMac87w==,iv:rpsez8LBKU5AzfJFmf/71yvkUrztqaRvS2Um3uEAHDk=,tag:sgXWifb+VwUpHIxMvsD8GA==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGs3dnNRRGoxZ3NCZWxj
            cDIyV3BNZnRCSVBYQVZyKytmRTY0aXRXNFNFCkpVVWtjTXF1YW51Y2U2L0NIcnNw
            NldyWFBadFBhR2JZY2hJa3UxQlY3ZEUKLS0tIEZTa3REMEE1NFFQNHE2RXZRRmpU
            Q1FIempZanpZNlRkRHJaL2h3bXp2T0UKlkxqr7LfA0+aaqyx1RABVdQq4E+Jc/df
            uG1tJOs5A8VPTO+4/fy0U0U7worgZaCEIliBld0ecO2MYnfK78/NnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T13:39:01Z"
    mac: ENC[AES256_GCM,data:AWdQKQ7/Znars9Xh07LLEdsWs6/vVaW+9jNIzoBKtK3vET1dfSYFlUB/RD6B8iK4/e6y2tu2BhGy5nQAJdXA+VOw8vaLz1O3ccD8qEQp6DNuq/gM/G4WvozBOLhfXgqZ0MxBPQ5WRMIGvAUNdQMZAjqC04SlEEFeHBrM1eKVi0A=,iv:k0svEn8bP0i2k++YXlW5wiCylPZzXxL67iyn3/VvTKY=,tag:TVeKam8qKHtn7bDMZkv+fg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
