PM_USER: ENC[AES256_GCM,data:Xe9W2O7zhFT6C64ImWwTGC65,iv:rGKH4+f7QgXMLd1pe5mbpgt7SLaf51C+kkQG7M+lwWw=,tag:vMpQ0OmclLO5/4ob6p4BGA==,type:str]
PM_PASS: ENC[AES256_GCM,data:r41P2dY0EwM=,iv:VcHI7XUAluUAc7ctGF4h+/wbV3/GVY0FLYu83I19GIk=,tag:NpWBRcnAkUy1k5ZLCiEdyw==,type:str]
MINIO_USERNAME: ENC[AES256_GCM,data:LBInQveXxH94LQ==,iv:kB24aMW6/640pm0wzcTKGLnYGWKspVBMqT1qd+CB9aA=,tag:a2UKx9KBzHoTwTsjHLaxtg==,type:str]
MINIO_PASSWORD: ENC[AES256_GCM,data:BD8wB1soUYUEpKBQtg==,iv:9YVIs/vUgJ9yHznW+gaqLeIMfYt0xE4kunOojYhpbJE=,tag:cWyjDxQwAlUeK3qOPqLXBQ==,type:str]
MINIO_ACCESS_KEY: ENC[AES256_GCM,data:DvPeEA==,iv:9gR+cWUBdwNU5N3cZNPewcOB5TIOTTn52pKuKUUbxVA=,tag:pPiJiRT/JtiNNZ3y4zsahQ==,type:str]
MINIO_SECRET_KEY: ENC[AES256_GCM,data:ngwWlvP3mZcuFxa9hk6fSSFkmpS8Xhza,iv:clrpMLMPJhAeJi/DCzP4tJYqE6Q618hs2C5zjfjNzXM=,tag:k6Gww0g2i/mgAnCyvbBQ8A==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGs3dnNRRGoxZ3NCZWxj
            cDIyV3BNZnRCSVBYQVZyKytmRTY0aXRXNFNFCkpVVWtjTXF1YW51Y2U2L0NIcnNw
            NldyWFBadFBhR2JZY2hJa3UxQlY3ZEUKLS0tIEZTa3REMEE1NFFQNHE2RXZRRmpU
            Q1FIempZanpZNlRkRHJaL2h3bXp2T0UKlkxqr7LfA0+aaqyx1RABVdQq4E+Jc/df
            uG1tJOs5A8VPTO+4/fy0U0U7worgZaCEIliBld0ecO2MYnfK78/NnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T11:28:25Z"
    mac: ENC[AES256_GCM,data:DWyOhOQICNmlPQZNmUth+H/J1HkhTXrQhJYJdl6DXD33lIduHEk2OSUUUDQGFh3uVz3a7+0lat9PGM6zMDDrXrbsfKhB1sFPY1i7HmItUVBFxp9ouvl/DznbKXCq01T5WWldTarpUM9vi7Unq232lfgPWOPYly3yvtnQRJNwehA=,iv:Zck2LgIZKFRVMmSejyN5g4wEfpaF8QnmZ+ha0xcVXSc=,tag:fzzrv42lbJkFTtokC2F+sw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
