#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR/../../.."

find . -type d -name ".terragrunt-stack" -exec rm -rf {} +

find . -type d -name ".terragrunt-cache" -exec rm -rf {} +

find . -type d -name ".terraform" -exec rm -rf {} +

find . -type f -name ".terraform.lock.hcl" -exec rm -f {} +
