#!/usr/bin/env bash

set -e

#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"
#USAGE flag "-a --auto-approve" help="Automatically approve the destroy action"

STACKS_DIR="$MISE_CONFIG_ROOT/examples/terragrunt/stacks"

if [[ -z "${usage_target:-}" ]]; then
  stack_dirs=()

  while IFS= read -r -d '' dir; do
    stack_dirs+=("$(basename "$dir")")
  done < <(find "$STACKS_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

  selected_stack=$(printf "%s\n" "${stack_dirs[@]}" | gum choose --header="Select a stack to operate on:")
else
  selected_stack+=("${usage_target}")
fi

cd "$STACKS_DIR/$selected_stack"

CMD="terragrunt stack run apply"

if [ "$usage_auto_approve" = "true" ]; then
  CMD="$CMD --non-interactive"
fi

echo ""
echo "🚀 Executing..."
echo "   Commands: $CMD"
echo "   Working dir: $(pwd)"
echo ""

if [ "$usage_dry_run" = "true" ]; then
  echo "Dry run mode. Command not executed."
  exit 0
fi

eval $CMD
