#! /usr/bin/env bash

set -e

mise run terragrunt:cleanup

# === TOFU ===

TOFUS=(
  naming
  proxmox-pool
  proxmox-vm
  proxmox-lxc
  dns
)

for TOFU in "${TOFUS[@]}"; do
  mise run tofu:init $TOFU
  sleep 1
  mise run tofu:plan $TOFU
  sleep 1
  mise run tofu:apply $TOFU
  sleep 1
done

for (( idx=${#TOFUS[@]}-1 ; idx>=0 ; idx-- )); do
  TOFU="${TOFUS[idx]}"
  mise run tofu:destroy $TOFU -a
  sleep 1
done

# === TERRAGRUNT UNITS ===

UNITS=(
  naming
  proxmox-pool
  proxmox-vm
  proxmox-lxc
  dns
)

for UNIT in "${UNITS[@]}"; do
  mise --raw run terragrunt:unit:plan $UNIT
  sleep 1
  mise --raw run terragrunt:unit:apply $UNIT
  sleep 1
done

for (( idx=${#UNITS[@]}-1 ; idx>=0 ; idx-- )); do
  UNIT="${UNITS[idx]}"
  mise --raw run terragrunt:unit:destroy $UNIT -a
  sleep 1
done

# === TERRAGRUNT STACKS ===

STACKS=(
  homelab-proxmox-container
  homelab-proxmox-vm
)

for STACK in "${STACKS[@]}"; do
  mise --raw run terragrunt:stack:plan $STACK -a
  sleep 1
  mise --raw run terragrunt:stack:apply $STACK -a
  sleep 1
  mise --raw run terragrunt:stack:destroy $STACK -a
done
