#!/usr/bin/env bash

#MISE description "Plan a Tofu unit"
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

set -e

# Source common functions
source "$MISE_CONFIG_ROOT/.mise/common.sh"

TOFU_DIR="$MISE_CONFIG_ROOT/examples/tofu"

if [[ -z "${usage_target:-}" ]]; then
  unit_dirs=()

  while IFS= read -r -d '' dir; do
    unit_dirs+=("$(basename "$dir")")
  done < <(find "$TOFU_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

  selected_unit=$(printf "%s\n" "${unit_dirs[@]}" | gum choose --header="Select a unit to operate on:")
else
  selected_unit+=("${usage_target}")
fi

cd "$TOFU_DIR/$selected_unit"

PLAN_FILE="${selected_unit}.tfplan"

CMD="tofu plan --var-file ${selected_unit}.tfvars -out=${PLAN_FILE} && tofu show -json ${PLAN_FILE} > ${PLAN_FILE}.tfgraph"

logCommand "$CMD" "$usage_dry_run"

eval $CMD
