#!/usr/bin/env bash
set -e

#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

UNITS_DIR="$MISE_CONFIG_ROOT/examples/terragrunt/units"

if [[ -z "${usage_target:-}" ]]; then
  unit_dirs=()

  # list all directories in examples/terragrunt/units and create a array of the names
  while IFS= read -r -d '' dir; do
    unit_dirs+=("$(basename "$dir")")
  done < <(find "$PROJECT_DIR/examples/terragrunt/units" -mindepth 1 -maxdepth 1 -type d -print0)

  selected_unit=$(printf "%s\n" "${unit_dirs[@]}" | gum choose --header="Select a unit to operate on:")
else
  selected_unit+=("${usage_target}")
fi

cd "$UNITS_DIR/$selected_unit"

TERRAGRUNT_APPLY_CMD="terragrunt apply --auto-approve"

echo ""
echo "🚀 Executing..."
echo "   Command: $TERRAGRUNT_APPLY_CMD"
echo "   Working dir: $(pwd)"
echo ""

if [ "$usage_dry_run" = "true" ]; then
  echo ""
  echo "Dry run mode. Command not executed."
  exit 0
fi

eval $TERRAGRUNT_APPLY_CMD
