#!/usr/bin/env bash

set -e

#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

UNITS_DIR="$MISE_CONFIG_ROOT/examples/terragrunt/units"

if [[ -z "${usage_target:-}" ]]; then
  # list all directories in examples/terragrunt/units and create a array of the names
  unit_dirs=()

  while IFS= read -r -d '' dir; do
    unit_dirs+=("$(basename "$dir")")
  done < <(find "$UNITS_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

  # Show a selection menu with gum to select a unit
  selected_unit=$(printf "%s\n" "${unit_dirs[@]}" | gum choose --header="Select a unit to operate on:")
fi

cd "$UNITS_DIR/$selected_unit"

TERRAGRUNT_DESTROY_CMD="terragrunt destroy"

echo ""
echo "🚀 Executing..."
echo "   Commands: $TERRAGRUNT_DESTROY_CMD"
echo "   Working dir: $(pwd)"
echo ""

if [ "$usage_dry_run" = "true" ]; then
  echo "Dry run mode. Command not executed."
  exit 0
fi

eval $TERRAGRUNT_DESTROY_CMD
